default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 599199
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: name_dev

test:
  <<: *default
  database: name_test
